(() => {
  'use strict';
  const COURSE=window.SYMBOLON_COURSE;
  const CARDS=window.SYMBOLON_CARDS;
  const ARCH=window.SYMBOLON_ARCHETYPES;
  const CASES=window.SYMBOLON_CASES||[];
  const AUDIO=window.SYMBOLON_AUDIO||{};
  const Cloud=window.SymbolonCloud||{isConfigured:()=>false};
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const STORAGE='symbolon_state_v1';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  const rand=a=>a[Math.floor(Math.random()*a.length)];
  const shuffle=a=>[...a].sort(()=>Math.random()-.5);
  const cardById=id=>CARDS.find(c=>c.id===id);
  const archByKey=k=>ARCH.find(a=>a.key===k);
  const now=()=>new Date().toISOString();

  const blank=()=>({
    completedModules:[],moduleExercises:{},moduleNotes:{},quizzes:{},
    cards:{},journal:[],practiceCount:0,caseCount:0,updatedAt:null,
    theme:'dark',large:false
  });
  function load(){let x={};try{x=JSON.parse(localStorage.getItem(STORAGE)||'{}')}catch{};return {...blank(),...x,cards:x.cards||{},journal:x.journal||[]};}
  const state=load();
  const cloud={configured:Cloud.isConfigured?.()||false,user:null,syncing:false,syncedUserId:null,timer:null,error:null};
  document.documentElement.dataset.theme=state.theme||'dark';document.body.classList.toggle('large',!!state.large);

  function snapshot(){const {theme,large,...rest}=state;return rest;}
  function persistLocal(){state.updatedAt=now();localStorage.setItem(STORAGE,JSON.stringify(state));updateProgressUi();}
  function persist(cloudToo=true){persistLocal();if(cloudToo)scheduleCloud();}
  function scheduleCloud(){if(!cloud.user||!cloud.configured)return;clearTimeout(cloud.timer);cloud.timer=setTimeout(async()=>{cloud.syncing=true;updateCloudUi();try{await Cloud.saveState(snapshot());cloud.error=null}catch(e){cloud.error=e.message||'Error de sincronización'}finally{cloud.syncing=false;updateCloudUi()}},650)}
  function applyRemote(r){if(!r)return;['completedModules','moduleExercises','moduleNotes','quizzes','cards','journal','practiceCount','caseCount','updatedAt'].forEach(k=>{if(r[k]!==undefined&&r[k]!==null)state[k]=r[k]});persistLocal();}
  async function syncAfterLogin(){if(!cloud.user||cloud.syncedUserId===cloud.user.id)return;cloud.syncing=true;updateCloudUi();try{const r=await Cloud.loadState();const lt=Date.parse(state.updatedAt||0)||0;const rt=Date.parse(r?.updatedAt||r?._cloudUpdatedAt||0)||0;if(r&&rt>lt)applyRemote(r);else await Cloud.saveState(snapshot());cloud.syncedUserId=cloud.user.id;cloud.error=null;renderNav();render()}catch(e){cloud.error=e.message||'No se pudo sincronizar'}finally{cloud.syncing=false;updateCloudUi()}}
  Cloud.init?.(({configured,user})=>{cloud.configured=configured;cloud.user=user;if(!user)cloud.syncedUserId=null;updateCloudUi();if(user)syncAfterLogin()});

  function toast(msg){const e=$('#toast');if(!e)return;e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
  function go(r){location.hash='#'+r;if(innerWidth<900)$('#sidebar')?.classList.remove('open')}
  function currentRoute(){return (location.hash||'#home').slice(1)}
  function cardState(id){return state.cards[id]||(state.cards[id]={status:'not',mastery:0,favorite:false,difficult:false,attempts:0,correct:0,lastSeen:null,nextReview:null});}
  function touchCard(id,kind='seen',correct=null){const s=cardState(id);s.lastSeen=now();if(s.status==='not')s.status='seen';if(kind==='practice'){s.attempts=(s.attempts||0)+1;if(correct===true)s.correct=(s.correct||0)+1;const raw=s.attempts?Math.round((s.correct/s.attempts)*100):0;s.mastery=clamp(Math.round(raw*.7 + Math.min(s.attempts,10)*3),0,100);if(s.mastery>=82&&s.attempts>=4)s.status='mastered';else if(s.attempts>=1)s.status='practicing';const days=s.mastery>=82?14:s.mastery>=60?7:s.mastery>=35?3:1;s.nextReview=new Date(Date.now()+days*86400000).toISOString()}persist();}
  function statusLabel(s){return ({not:'No estudiada',seen:'Vista',practicing:'Practicando',mastered:'Dominada'})[s]||'No estudiada'}
  function statusClass(s){return s==='mastered'?'mastered':s==='practicing'?'practicing':s==='seen'?'seen':''}
  function masteryStats(){const arr=CARDS.map(c=>cardState(c.id));return{seen:arr.filter(x=>x.status!=='not').length,mastered:arr.filter(x=>x.status==='mastered').length,practicing:arr.filter(x=>x.status==='practicing').length,favorites:arr.filter(x=>x.favorite).length,difficult:arr.filter(x=>x.difficult).length,avg:Math.round(arr.reduce((a,b)=>a+(b.mastery||0),0)/arr.length)}}
  function updateProgressUi(){const m=masteryStats();const pct=Math.round(m.mastered/CARDS.length*100);if($('#overallBar'))$('#overallBar').style.width=pct+'%';if($('#progressText'))$('#progressText').textContent=`${m.mastered} / 78 cartas`;if($('#progressPct'))$('#progressPct').textContent=pct+'%'}
  function cloudLabel(){if(!cloud.configured)return'Activar nube';if(cloud.syncing)return'Sincronizando…';if(cloud.user)return'✓ '+(cloud.user.email?.split('@')[0]||'Cuenta');return'Entrar'}
  function updateCloudUi(){const b=$('#accountBtn');if(b){b.textContent=cloudLabel();b.classList.toggle('cloud-ok',!!cloud.user)}const s=$('#cloudStatus');if(s)s.textContent=cloud.error?cloud.error:(cloud.user?'Sincronizado en tus dispositivos':cloud.configured?'Inicia sesión para sincronizar':'Supabase no configurado')}

  function renderNav(){const r=currentRoute();$('#moduleNav').innerHTML=COURSE.modules.map(m=>`<button data-module="${m.id}" class="${r===`module/${m.id}`?'active':''} ${state.completedModules.includes(m.id)?'done':''}"><span class="num">${m.number}</span><span>${esc(m.title)}</span></button>`).join('');$$('[data-module]').forEach(b=>b.onclick=()=>go('module/'+b.dataset.module));$$('[data-route]').forEach(b=>{b.onclick=()=>go(b.dataset.route);b.classList.toggle('active',r===b.dataset.route||(b.dataset.route==='course'&&r.startsWith('module/'))||(b.dataset.route==='cards'&&r.startsWith('card/'))||(b.dataset.route==='practice'&&r.startsWith('practice/')))});updateProgressUi()}

  function heroCloud(){return `<div class="cloud-banner ${cloud.user?'ok':''}"><span class="cloud-dot"></span><div><strong>${cloud.user?'Tu estudio está sincronizado':cloud.configured?'Sincronización preparada':'Guardado local activo'}</strong><span id="cloudStatus"></span></div><button class="mini" id="homeAccountBtn">${cloudLabel()}</button></div>`}
  function home(){const m=masteryStats();const done=state.completedModules.length;return `<div class="content"><section class="hero"><div><div class="page-kicker">CURSO · BIBLIOTECA · ENTRENADOR · DIARIO</div><h1>El juego<br>del <em>recuerdo.</em></h1><p>${esc(COURSE.meta.principle)} Aprende a mirar una carta, reconocer sus personas internas, comprender la relación entre ellas y construir una lectura con criterio.</p><div class="hero-actions"><button class="primary" id="startBtn">${done?'Continuar aprendiendo':'Empezar el curso'}</button><button class="secondary" id="practiceBtn">Practicar ahora</button><button class="secondary" id="cardsBtn">Explorar las 78</button></div>${heroCloud()}</div><div class="hero-art"><div class="hero-wheel"><div class="hero-zodiac">♈ ♉ ♊ ♋<br>♌ ♍ ♎ ♏<br>♐ ♑ ♒ ♓</div></div></div></section><div class="stats"><div class="stat"><strong>${done}/13</strong><span>módulos completados</span></div><div class="stat"><strong>${m.seen}/78</strong><span>cartas estudiadas</span></div><div class="stat"><strong>${m.mastered}/78</strong><span>cartas dominadas</span></div><div class="stat"><strong>${state.journal.length}</strong><span>lecturas guardadas</span></div></div><div class="notice"><strong>Marco del curso.</strong> ${esc(COURSE.meta.disclaimer)}</div><div class="section-head"><div><div class="page-kicker">RECORRIDO</div><h2>Aprender el sistema</h2></div><p>Del lenguaje visual a una lectura completa sin depender de memorizar definiciones.</p></div>${moduleCards()}</div>`}
  function moduleCards(){return `<div class="module-grid">${COURSE.modules.map(m=>`<article class="module-card ${state.completedModules.includes(m.id)?'done':''}" data-open-module="${m.id}"><div class="top"><span>MÓDULO ${m.number}</span><span>${m.duration}</span></div><h3>${esc(m.title)}</h3><p>${esc(m.subtitle)}</p><div class="card-flags"><span>4 láminas</span><span>Práctica</span><span>Test</span></div></article>`).join('')}</div>`}
  function coursePage(){return `<div class="content"><div class="page-kicker">APRENDER</div><h1 class="page-title">Del símbolo<br>al criterio.</h1><p class="page-lede">Trece módulos progresivos. Cada uno añade una capa: observación, arquetipos, combinaciones, posiciones, lectura y entrenamiento.</p>${moduleCards()}</div>`}

  function modulePage(id){const m=COURSE.modules.find(x=>x.id===id);if(!m)return notFound();const ex=state.moduleExercises[id]||'';const note=state.moduleNotes[id]||'';const qstate=state.quizzes[id];return `<div class="content"><section class="module-hero"><div class="page-kicker">MÓDULO ${m.number}</div><h1>${esc(m.title)}</h1><p>${esc(m.subtitle)}</p><div class="module-controls"><button class="primary" id="audioModule">▶ Escuchar módulo</button><button class="secondary" id="completeModule">${state.completedModules.includes(id)?'✓ Completado':'Marcar como completado'}</button><button class="secondary" id="randomCardModule">Practicar una carta</button></div></section><div class="section-head"><div><div class="page-kicker">MAPA VISUAL</div><h2>Antes de entrar al detalle</h2></div><p>Abre cada lámina a tamaño completo. Están pensadas para fijar la estructura del módulo.</p></div><div class="slides-grid">${m.slides.map((s,i)=>`<article class="slide-card" data-slide="${i}"><img src="${s.image}" alt="${esc(s.title)}"></article>`).join('')}</div>${m.sections.map((s,i)=>`<section class="lesson-block"><div class="lesson-index">0${i+1}</div><div><h2>${esc(s.title)}</h2><p>${esc(s.body)}</p></div></section>`).join('')}<section class="exercise"><div class="page-kicker">EJERCICIO INTEGRADO</div><h3>${esc(m.exercise.title)}</h3><p>${esc(m.exercise.prompt)}</p><textarea id="moduleExercise" placeholder="Escribe aquí. Se guarda automáticamente.">${esc(ex)}</textarea><div class="autosave">Guardado automático local + nube cuando tu cuenta está activa.</div></section><section class="notes-box"><div class="page-kicker">TUS NOTAS</div><textarea id="moduleNotes" placeholder="Ideas, asociaciones, dudas o cartas que quieras revisar…">${esc(note)}</textarea></section>${quizHtml(m,qstate)}<div class="hero-actions"><button class="primary" id="finishModule">${state.completedModules.includes(id)?'✓ Módulo completado':'Completar módulo y continuar'}</button></div></div>`}
  function quizHtml(m,qstate){return `<section class="quiz"><div class="page-kicker">TEST DEL MÓDULO</div><h3>Comprueba el razonamiento</h3>${m.quiz.map((q,qi)=>`<div class="quiz-q"><strong>${qi+1}. ${esc(q.q)}</strong><div class="quiz-options">${q.options.map((o,oi)=>`<label><input type="radio" name="q${qi}" value="${oi}" ${qstate?.answers?.[qi]===oi?'checked':''}><span>${esc(o)}</span></label>`).join('')}</div></div>`).join('')}<button class="primary" id="checkQuiz">Corregir test</button>${qstate?`<div class="quiz-result"><strong>${qstate.score}/${m.quiz.length}</strong> · ${qstate.passed?'Superado':'Revisa el módulo y prueba de nuevo.'}</div>`:''}</section>`}

  let cardFilters={q:'',family:'all',status:'all',fav:false,difficult:false};
  function filteredCards(){let a=CARDS;const f=cardFilters;if(f.q){const q=f.q.toLowerCase();a=a.filter(c=>[c.title,c.titleEn,c.signA,c.signB,c.planetA,c.planetB,c.idea,...c.keywords].filter(Boolean).join(' ').toLowerCase().includes(q))}if(f.family!=='all')a=a.filter(c=>c.family===f.family);if(f.status!=='all')a=a.filter(c=>cardState(c.id).status===f.status);if(f.fav)a=a.filter(c=>cardState(c.id).favorite);if(f.difficult)a=a.filter(c=>cardState(c.id).difficult);return a}
  function cardsPage(){const list=filteredCards();return `<div class="content"><div class="page-kicker">BIBLIOTECA</div><h1 class="page-title">Las 78 cartas</h1><p class="page-lede">Busca por carta, signo, planeta o idea. Cada ficha separa estructura arquetípica, dinámica psicológica y las tres posiciones de lectura.</p><div class="toolbar"><div class="search"><input id="cardSearch" placeholder="Buscar carta, signo, planeta…" value="${esc(cardFilters.q)}"></div><select id="familyFilter"><option value="all">Todas</option><option value="fundamental" ${cardFilters.family==='fundamental'?'selected':''}>12 fundamentales</option><option value="luna" ${cardFilters.family==='luna'?'selected':''}>Luna</option><option value="sol" ${cardFilters.family==='sol'?'selected':''}>Sol</option><option value="combinada" ${cardFilters.family==='combinada'?'selected':''}>Combinaciones</option></select><select id="statusFilter"><option value="all">Cualquier estado</option><option value="not" ${cardFilters.status==='not'?'selected':''}>No estudiadas</option><option value="seen" ${cardFilters.status==='seen'?'selected':''}>Vistas</option><option value="practicing" ${cardFilters.status==='practicing'?'selected':''}>Practicando</option><option value="mastered" ${cardFilters.status==='mastered'?'selected':''}>Dominadas</option></select><button class="filter-chip ${cardFilters.fav?'active':''}" id="favFilter">★ Favoritas</button><button class="filter-chip ${cardFilters.difficult?'active':''}" id="diffFilter">! Difíciles</button></div><div class="section-head"><div><div class="page-kicker">MATRIZ</div><h2>12 × 12</h2></div><p>La diagonal son las 12 cartas fundamentales; el resto de la mitad superior contiene las 66 combinaciones.</p></div>${matrixHtml()}<div class="section-head"><div><div class="page-kicker">RESULTADOS</div><h2>${list.length} cartas</h2></div></div><div id="cardGrid" class="card-grid">${list.map(cardTile).join('')}</div></div>`}
  function cardTile(c){const s=cardState(c.id);return `<article class="symbolon-card" data-card="${c.id}"><span class="fav-star">${s.favorite?'★':'☆'}</span><span class="state-badge">${statusLabel(s.status)}</span><img src="${c.image}" alt="Carta ${esc(c.title)}"><div class="body"><div class="number">${String(c.number).padStart(2,'0')} · ${esc(c.family)}</div><h3>${esc(c.title)}</h3><div class="astro">${esc(c.glyphA)} ${esc(c.signA)}${c.signB?` + ${esc(c.glyphB)} ${esc(c.signB)}`:''}</div></div></article>`}
  function matrixHtml(){const idx={};CARDS.forEach(c=>{if(!c.b)idx[c.a+'|'+c.a]=c;else{idx[c.a+'|'+c.b]=c;idx[c.b+'|'+c.a]=c}});return `<div class="matrix">${ARCH.flatMap((r,ri)=>ARCH.map((col,ci)=>{if(ci<ri)return`<div class="matrix-cell blank"></div>`;const c=idx[r.key+'|'+col.key];if(!c)return`<div class="matrix-cell blank"></div>`;const s=cardState(c.id);return`<button class="matrix-cell ${statusClass(s.status)}" data-card="${c.id}" title="${esc(c.title)}">${ri===ci?esc(r.glyph):c.number}</button>`})).join('')}</div><div class="matrix-legend"><span>◻ No estudiada</span><span>□ Vista</span><span>▣ Practicando</span><span>■ Dominada</span></div>`}

  function cardDetail(id){const c=cardById(id);if(!c)return notFound();const s=cardState(id);if(s.status==='not'){s.status='seen';s.lastSeen=now();persist()}const a=archByKey(c.a),b=c.b?archByKey(c.b):null;return `<div class="content"><button class="secondary" id="backCards">← Biblioteca</button><div class="card-detail" style="margin-top:18px"><div class="sticky"><img src="${c.image}" alt="${esc(c.title)}"><div class="state-controls"><button data-status="seen" class="${s.status==='seen'?'active':''}">Vista</button><button data-status="practicing" class="${s.status==='practicing'?'active':''}">Practicando</button><button data-status="mastered" class="${s.status==='mastered'?'active':''}">Dominada</button><button id="favoriteCard" class="${s.favorite?'active':''}">${s.favorite?'★':'☆'} Favorita</button><button id="difficultCard" class="${s.difficult?'active':''}">! Difícil</button></div><button class="primary" id="practiceThis">Practicar esta carta</button></div><div><div class="detail-title"><div class="page-kicker">CARTA ${String(c.number).padStart(2,'0')} · ${esc(c.family)}</div><h1>${esc(c.title)}</h1><div class="astro-big">${esc(c.glyphA)} ${esc(c.signA)} · ${esc(c.planetGlyphA)} ${esc(c.planetA)}${b?` &nbsp;×&nbsp; ${esc(c.glyphB)} ${esc(c.signB)} · ${esc(c.planetGlyphB)} ${esc(c.planetB)}`:''}</div></div><section class="detail-section"><div class="page-kicker">IDEA ESENCIAL</div><h2>${esc(c.idea)}</h2><div class="tag-list">${c.keywords.map(k=>`<span class="tag">${esc(k)}</span>`).join('')}</div></section><section class="detail-section"><h2>La dinámica psicológica</h2><p>${esc(c.psychology)}</p></section><section class="detail-section"><div class="triple"><div class="position-card"><strong>Deseo</strong><p>${esc(c.desire)}</p></div><div class="position-card"><strong>Miedo</strong><p>${esc(c.fear)}</p></div><div class="position-card"><strong>Sombra</strong><p>${esc(c.shadow)}</p></div></div><div class="position-card" style="margin-top:10px"><strong>Potencial consciente</strong><p>${esc(c.potential)}</p></div></section><section class="detail-section"><h2>Problema · Camino · Resultado</h2><div class="triple"><div class="position-card"><strong>Problema</strong><p>${esc(c.problem)}</p></div><div class="position-card"><strong>Camino</strong><p>${esc(c.way)}</p></div><div class="position-card"><strong>Resultado</strong><p>${esc(c.result)}</p></div></div></section><section class="detail-section"><h2>En la vida cotidiana</h2><ul>${c.examples.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section><section class="detail-section"><h2>Pregunta para ti</h2><p>${esc(c.question)}</p><div class="notice"><strong>Frase para recordarla.</strong> ${esc(c.remember)}</div></section><section class="detail-section"><small style="color:var(--muted)">${esc(c.sourceNote)}</small></section></div></div></div>`}

  function practicePage(){return `<div class="content"><div class="page-kicker">ENTRENADOR</div><h1 class="page-title">Practicar</h1><p class="page-lede">Elige qué habilidad quieres entrenar. Cada intento actualiza el dominio de las cartas y las que fallas vuelven a aparecer antes.</p><div class="practice-grid"><article class="practice-mode" data-mode="archetypes"><div class="icon">♊×♄</div><h3>Reconoce los arquetipos</h3><p>Se muestra una carta y eliges la pareja correcta de principios.</p></article><article class="practice-mode" data-mode="build"><div class="icon">◐</div><h3>Construye el significado</h3><p>Recibes dos arquetipos, escribes tu hipótesis y luego comparas.</p></article><article class="practice-mode" data-mode="position"><div class="icon">ⅠⅡⅢ</div><h3>Problema · Camino · Resultado</h3><p>Una carta aparece en una posición aleatoria y debes adaptarla.</p></article><article class="practice-mode" data-mode="surprise"><div class="icon">✦✦✦</div><h3>Tirada sorpresa</h3><p>Tres cartas aleatorias para construir una secuencia completa.</p></article><article class="practice-mode" data-mode="case"><div class="icon">◎</div><h3>Caso práctico</h3><p>Pregunta realista, respuesta escrita y lectura razonada.</p></article><article class="practice-mode" data-mode="review"><div class="icon">↻</div><h3>Repaso de errores</h3><p>Prioriza cartas difíciles y las que tienen menor porcentaje de dominio.</p></article></div></div>`}
  let session=null;
  function pickPracticeCard(review=false,forced=null){if(forced)return cardById(forced);let pool=CARDS;if(review){pool=CARDS.filter(c=>{const s=cardState(c.id);return s.difficult||s.status==='practicing'||(s.attempts>0&&s.mastery<70)});if(!pool.length)pool=CARDS}return rand(pool)}
  function practiceSession(mode,forced=null){session={mode,card:pickPracticeCard(mode==='review',forced),revealed:false,answer:''};if(mode==='case')session.case=rand(CASES);return practiceSessionHtml()}
  function practiceSessionHtml(){const s=session;if(!s)return practicePage();if(s.mode==='archetypes'||s.mode==='review'){const c=s.card;const correct=c.b?[c.a,c.b]:[c.a];const distract=shuffle(ARCH.filter(a=>!correct.includes(a.key))).slice(0,c.b?6:3);let opts;if(c.b){opts=shuffle([[c.a,c.b],...Array.from({length:3},(_,i)=>[rand(ARCH).key,distract[i]?.key||rand(ARCH).key]).map(p=>p[0]===p[1]?[p[0],rand(ARCH.filter(x=>x.key!==p[0])).key]:p)]).slice(0,4)}else opts=shuffle([[c.a],...distract.slice(0,3).map(x=>[x.key])]);session.options=opts;return `<div class="content practice-session"><button class="secondary" id="practiceBack">← Modos</button><div class="page-kicker">RECONOCE LOS ARQUETIPOS</div><h1 class="page-title">¿Quiénes están aquí?</h1><div class="prompt-card"><img class="practice-card-image" src="${c.image}" alt="${esc(c.title)}"><div class="choice-grid">${opts.map((p,i)=>`<button data-choice="${i}">${p.map(k=>{const a=archByKey(k);return`${a.glyph} ${a.sign}`}).join(' + ')}</button>`).join('')}</div><div id="practiceFeedback"></div></div><button class="secondary" id="nextPractice">Otra carta</button></div>`}
    if(s.mode==='build'){const c=s.card,a=archByKey(c.a),b=c.b?archByKey(c.b):null;return `<div class="content practice-session"><button class="secondary" id="practiceBack">← Modos</button><div class="page-kicker">CONSTRUYE EL SIGNIFICADO</div><h1 class="page-title">${a.glyph} ${a.sign}${b?` × ${b.glyph} ${b.sign}`:''}</h1><p class="page-lede">Antes de saber qué carta es, escribe qué cooperación o conflicto podría nacer entre estas funciones.</p><div class="prompt-card"><textarea id="practiceAnswer" style="width:100%;min-height:170px;background:var(--bg);color:var(--text);border:1px solid var(--line);border-radius:14px;padding:14px" placeholder="¿Qué quiere cada parte? ¿Dónde chocan? ¿Cuál podría ser el potencial consciente?"></textarea><button class="primary" id="revealPractice" style="margin-top:12px">Ver la carta y comparar</button>${s.revealed?`<div class="feedback"><strong>${esc(c.title)}</strong><br>${esc(c.idea)}<br><br>${esc(c.psychology)}</div><img class="practice-card-image" style="margin-top:16px" src="${c.image}">`:''}</div><button class="secondary" id="nextPractice">Otra combinación</button></div>`}
    if(s.mode==='position'){const c=s.card;session.position=session.position||rand(['Problema','Camino','Resultado']);const key=session.position==='Problema'?'problem':session.position==='Camino'?'way':'result';return `<div class="content practice-session"><button class="secondary" id="practiceBack">← Modos</button><div class="page-kicker">POSICIÓN ALEATORIA</div><h1 class="page-title">${session.position}</h1><div class="prompt-card"><img class="practice-card-image" src="${c.image}"><h2 style="font-family:var(--serif);font-weight:400">${esc(c.title)}</h2><textarea id="practiceAnswer" style="width:100%;min-height:150px;background:var(--bg);color:var(--text);border:1px solid var(--line);border-radius:14px;padding:14px" placeholder="Interpreta esta carta específicamente como ${session.position.toLowerCase()}…"></textarea><button class="primary" id="revealPractice" style="margin-top:12px">Comparar</button>${s.revealed?`<div class="feedback">${esc(c[key])}</div>`:''}</div><button class="secondary" id="nextPractice">Otra carta</button></div>`}
    if(s.mode==='surprise'){session.cards=session.cards||shuffle(CARDS).slice(0,3);return `<div class="content practice-session"><button class="secondary" id="practiceBack">← Modos</button><div class="page-kicker">TIRADA SORPRESA</div><h1 class="page-title">Problema → Camino → Resultado</h1><div class="triple" style="margin:20px 0">${session.cards.map((c,i)=>`<div class="position-card"><strong>${['Problema','Camino','Resultado'][i]}</strong><img src="${c.image}" style="width:100%;border-radius:12px"><p>${esc(c.title)}</p></div>`).join('')}</div><div class="prompt-card"><textarea id="practiceAnswer" style="width:100%;min-height:180px;background:var(--bg);color:var(--text);border:1px solid var(--line);border-radius:14px;padding:14px" placeholder="Construye el hilo narrativo. ¿Qué cambia de la primera a la tercera carta?"></textarea><button class="primary" id="revealPractice" style="margin-top:12px">Ver claves</button>${s.revealed?`<div class="feedback"><strong>Problema:</strong> ${esc(session.cards[0].problem)}<br><br><strong>Camino:</strong> ${esc(session.cards[1].way)}<br><br><strong>Resultado:</strong> ${esc(session.cards[2].result)}</div>`:''}</div><button class="secondary" id="nextPractice">Nueva tirada</button></div>`}
    if(s.mode==='case'){const k=s.case;const cs=k.cards.map(cardById);return `<div class="content practice-session"><button class="secondary" id="practiceBack">← Modos</button><div class="page-kicker">CASO · ${esc(k.theme)}</div><h1 class="page-title">${esc(k.question)}</h1><div class="triple" style="margin:20px 0">${cs.map((c,i)=>`<div class="position-card"><strong>${esc(k.positions[i])}</strong><img src="${c.image}" style="width:100%;border-radius:12px"><p>${esc(c.title)}</p></div>`).join('')}</div><div class="prompt-card"><div class="tag-list">${k.keys.map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div><textarea id="practiceAnswer" style="width:100%;min-height:180px;background:var(--bg);color:var(--text);border:1px solid var(--line);border-radius:14px;padding:14px;margin-top:12px" placeholder="Escribe tu lectura razonada antes de abrir la propuesta…"></textarea><button class="primary" id="revealPractice" style="margin-top:12px">Mostrar lectura razonada</button>${s.revealed?`<div class="feedback">${esc(k.reasoning)}</div>`:''}</div><button class="secondary" id="nextPractice">Otro caso</button></div>`}
    return practicePage();
  }

  function journalPage(){return `<div class="content"><div class="page-kicker">MI DIARIO SYMBOLON</div><h1 class="page-title">Lecturas que<br>siguen vivas.</h1><p class="page-lede">Registra la interpretación inicial y vuelve días después. El seguimiento convierte cada lectura en aprendizaje.</p><div class="journal-layout"><div class="form-card"><h2 style="font-family:var(--serif);font-weight:400">Nueva lectura</h2><div class="field"><label>Fecha</label><input id="jDate" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Tema</label><select id="jTheme"><option>Relaciones</option><option>Trabajo</option><option>Dinero</option><option>Familia</option><option>Decisión</option><option>Creatividad</option><option>Propósito</option><option>Otro</option></select></div><div class="field"><label>Pregunta</label><textarea id="jQuestion" placeholder="¿Qué necesito reconocer sobre…?"></textarea></div><div class="field"><label>Tirada</label><select id="jSpread"><option>Una carta</option><option>Dos cartas</option><option selected>Problema · Camino · Resultado</option><option>Otra</option></select></div>${[1,2,3].map(i=>`<div class="field"><label>Carta ${i}</label><select id="jCard${i}"><option value="">—</option>${CARDS.map(c=>`<option value="${c.id}">${String(c.number).padStart(2,'0')} · ${esc(c.title)}</option>`).join('')}</select></div>`).join('')}<div class="field"><label>Interpretación inicial</label><textarea id="jInitial"></textarea></div><div class="field"><label>Emociones / cuerpo</label><textarea id="jEmotions"></textarea></div><div class="field"><label>Conclusión o acción</label><textarea id="jConclusion"></textarea></div><button class="primary" id="saveJournal">Guardar lectura</button></div><div><div class="toolbar"><div class="search"><input id="journalSearch" placeholder="Filtrar por pregunta, tema o carta…"></div></div><div id="journalList" class="journal-list">${journalListHtml('')}</div></div></div></div>`}
  function journalListHtml(q=''){q=q.toLowerCase();let list=[...state.journal].sort((a,b)=>String(b.date).localeCompare(String(a.date)));if(q)list=list.filter(j=>JSON.stringify(j).toLowerCase().includes(q)||j.cards.some(id=>cardById(id)?.title.toLowerCase().includes(q)));if(!list.length)return`<div class="panel"><p style="color:var(--muted)">Aún no hay lecturas guardadas.</p></div>`;return list.map(j=>`<article class="journal-card" data-jid="${j.id}"><div class="meta">${esc(j.date)} · ${esc(j.theme)} · ${esc(j.spread)}</div><h3>${esc(j.question||'Lectura sin título')}</h3><div class="tag-list">${j.cards.filter(Boolean).map(id=>`<span class="tag">${esc(cardById(id)?.title||id)}</span>`).join('')}</div><p><strong>Inicial:</strong> ${esc(j.initial||'—')}</p><p><strong>Conclusión:</strong> ${esc(j.conclusion||'—')}</p>${j.followup?`<p><strong>Seguimiento:</strong> ${esc(j.followup)}</p>`:''}<div class="journal-actions"><button data-follow="${j.id}">Añadir seguimiento</button><button data-delete-j="${j.id}">Eliminar</button></div></article>`).join('')}

  function progressPage(){const m=masteryStats();const quizPassed=Object.values(state.quizzes).filter(q=>q?.passed).length;const due=CARDS.filter(c=>{const s=cardState(c.id);return s.nextReview&&Date.parse(s.nextReview)<=Date.now()}).length;const rows=ARCH.map(a=>{const rel=CARDS.filter(c=>c.a===a.key||c.b===a.key);const avg=Math.round(rel.reduce((sum,c)=>sum+(cardState(c.id).mastery||0),0)/rel.length);return{a,avg}}).sort((x,y)=>y.avg-x.avg);return `<div class="content"><div class="page-kicker">MI PROGRESO</div><h1 class="page-title">Tu mapa de<br>dominio.</h1><p class="page-lede">El porcentaje no pretende medir intuición. Resume exposición, práctica y aciertos para ayudarte a decidir qué revisar.</p><div class="progress-grid"><div class="metric"><strong>${state.completedModules.length}/13</strong><span>módulos completados</span></div><div class="metric"><strong>${m.mastered}/78</strong><span>cartas dominadas</span></div><div class="metric"><strong>${quizPassed}/13</strong><span>tests superados</span></div><div class="metric"><strong>${state.practiceCount}</strong><span>prácticas realizadas</span></div><div class="metric"><strong>${m.avg}%</strong><span>dominio medio</span></div><div class="metric"><strong>${m.difficult}</strong><span>cartas difíciles</span></div><div class="metric"><strong>${due}</strong><span>revisiones vencidas</span></div><div class="metric"><strong>${state.journal.length}</strong><span>lecturas en el diario</span></div></div><div class="section-head"><div><div class="page-kicker">POR ARQUETIPO</div><h2>Fortalezas y huecos</h2></div></div><div class="mastery-list">${rows.map(r=>`<div class="mastery-row"><span>${r.a.glyph} ${esc(r.a.name)} · ${esc(r.a.sign)}</span><div class="bar"><i style="width:${r.avg}%"></i></div><small>${r.avg}%</small></div>`).join('')}</div><div class="hero-actions" style="margin-top:22px"><button class="primary" id="reviewNow">Repasar cartas débiles</button><button class="secondary" id="allCardsProgress">Ver biblioteca</button></div></div>`}

  function sourcesPage(){return `<div class="content"><div class="page-kicker">FUENTES Y MÉTODO</div><h1 class="page-title">Qué es fuente<br>y qué es pedagogía.</h1><p class="page-lede">La estructura del sistema se contrasta con información pública. Las fichas, ejercicios, ejemplos y explicaciones del curso están redactados de cero y no reproducen el manual oficial.</p><div class="notice"><strong>Imágenes.</strong> Las imágenes incluidas en este ZIP son láminas pedagógicas originales creadas para el curso. No son copias de las ilustraciones oficiales de Thea Weller. La arquitectura permite sustituirlas más adelante por imágenes autorizadas sin tocar la lógica de la aplicación.</div><div class="source-list">${Object.values(COURSE.sources).map(s=>`<article class="source-item"><a href="${s.url}" target="_blank" rel="noopener">${esc(s.title)}</a><p>${esc(s.note)}</p></article>`).join('')}</div></div>`}
  function settingsPage(){return `<div class="content"><div class="page-kicker">AJUSTES</div><h1 class="page-title">Tu experiencia</h1><div class="settings-list"><div class="setting-row"><div><strong>Cuenta y nube</strong><p>${cloud.user?'Sesión iniciada como '+esc(cloud.user.email):'Sincroniza progreso, ejercicios, cartas y diario entre dispositivos.'}</p></div><button class="secondary" id="settingsAccount">${cloud.user?'Cerrar sesión':'Entrar'}</button></div><div class="setting-row"><div><strong>Modo visual</strong><p>Alterna entre grafito y marfil.</p></div><button class="secondary" id="settingsTheme">${state.theme==='dark'?'Cambiar a claro':'Cambiar a oscuro'}</button></div><div class="setting-row"><div><strong>Tamaño de texto</strong><p>Aumenta la tipografía de lectura.</p></div><button class="secondary" id="settingsFont">${state.large?'Tamaño normal':'Texto grande'}</button></div><div class="setting-row"><div><strong>Datos locales</strong><p>Reinicia progreso, respuestas y diario de este dispositivo. La nube no se borra automáticamente.</p></div><button class="secondary" id="resetLocal">Reiniciar local</button></div></div></div>`}
  function notFound(){return`<div class="content"><h1 class="page-title">No encontrado</h1><button class="primary" onclick="location.hash='#home'">Volver</button></div>`}

  function render(){const route=currentRoute();renderNav();let html;if(route==='home')html=home();else if(route==='course')html=coursePage();else if(route.startsWith('module/'))html=modulePage(route.split('/')[1]);else if(route==='cards')html=cardsPage();else if(route.startsWith('card/'))html=cardDetail(route.split('/')[1]);else if(route==='practice')html=practicePage();else if(route.startsWith('practice/')){const parts=route.split('/');html=practiceSession(parts[1],parts[2]||null)}else if(route==='journal')html=journalPage();else if(route==='progress')html=progressPage();else if(route==='sources')html=sourcesPage();else if(route==='settings')html=settingsPage();else html=notFound();$('#app').innerHTML=html;bind(route);$('#app').focus({preventScroll:true});scrollTo(0,0);updateCloudUi();updateProgressUi()}

  function bind(route){
    $$('[data-open-module]').forEach(x=>x.onclick=()=>go('module/'+x.dataset.openModule));
    $('#startBtn')?.addEventListener('click',()=>{const next=COURSE.modules.find(m=>!state.completedModules.includes(m.id))||COURSE.modules[0];go('module/'+next.id)});
    $('#practiceBtn')?.addEventListener('click',()=>go('practice'));$('#cardsBtn')?.addEventListener('click',()=>go('cards'));$('#homeAccountBtn')?.addEventListener('click',accountAction);
    if(route.startsWith('module/')) bindModule(route.split('/')[1]);
    if(route==='cards') bindCards();
    if(route.startsWith('card/')) bindCard(route.split('/')[1]);
    if(route==='practice') $$('[data-mode]').forEach(x=>x.onclick=()=>go('practice/'+x.dataset.mode));
    if(route.startsWith('practice/')) bindPractice();
    if(route==='journal') bindJournal();
    if(route==='progress'){ $('#reviewNow')?.addEventListener('click',()=>go('practice/review'));$('#allCardsProgress')?.addEventListener('click',()=>go('cards')); }
    if(route==='settings') bindSettings();
  }
  function bindModule(id){const m=COURSE.modules.find(x=>x.id===id);$$('[data-slide]').forEach(x=>x.onclick=()=>{const s=m.slides[+x.dataset.slide];showModal(`<img src="${s.image}" alt="${esc(s.title)}">`)});const ex=$('#moduleExercise');if(ex)ex.oninput=()=>{state.moduleExercises[id]=ex.value;persist()};const no=$('#moduleNotes');if(no)no.oninput=()=>{state.moduleNotes[id]=no.value;persist()};const toggle=()=>{if(state.completedModules.includes(id))state.completedModules=state.completedModules.filter(x=>x!==id);else state.completedModules.push(id);persist();render()};$('#completeModule')?.addEventListener('click',toggle);$('#finishModule')?.addEventListener('click',()=>{if(!state.completedModules.includes(id))state.completedModules.push(id);persist();const i=COURSE.modules.findIndex(x=>x.id===id);go(i<COURSE.modules.length-1?'module/'+COURSE.modules[i+1].id:'progress')});$('#checkQuiz')?.addEventListener('click',()=>{const answers=m.quiz.map((q,i)=>{const el=$(`input[name="q${i}"]:checked`);return el?+el.value:null});const score=m.quiz.reduce((n,q,i)=>n+(answers[i]===q.answer?1:0),0);state.quizzes[id]={answers,score,passed:score>=3,at:now()};persist();render()});$('#audioModule')?.addEventListener('click',()=>startAudio(id,m.title));$('#randomCardModule')?.addEventListener('click',()=>go('practice/build'))}
  function bindCards(){const refresh=()=>{const grid=$('#cardGrid');if(grid)grid.innerHTML=filteredCards().map(cardTile).join('');bindCardTiles()};$('#cardSearch')?.addEventListener('input',e=>{cardFilters.q=e.target.value;refresh()});$('#familyFilter')?.addEventListener('change',e=>{cardFilters.family=e.target.value;refresh()});$('#statusFilter')?.addEventListener('change',e=>{cardFilters.status=e.target.value;refresh()});$('#favFilter')?.addEventListener('click',()=>{cardFilters.fav=!cardFilters.fav;render()});$('#diffFilter')?.addEventListener('click',()=>{cardFilters.difficult=!cardFilters.difficult;render()});bindCardTiles();$$('.matrix-cell[data-card]').forEach(x=>x.onclick=()=>go('card/'+x.dataset.card))}
  function bindCardTiles(){$$('.symbolon-card[data-card]').forEach(x=>x.onclick=e=>{if(e.target.classList.contains('fav-star')){const s=cardState(x.dataset.card);s.favorite=!s.favorite;persist();e.target.textContent=s.favorite?'★':'☆';return}go('card/'+x.dataset.card)})}
  function bindCard(id){$('#backCards')?.addEventListener('click',()=>go('cards'));$$('[data-status]').forEach(b=>b.onclick=()=>{const s=cardState(id);s.status=b.dataset.status;if(s.status==='mastered')s.mastery=Math.max(82,s.mastery||0);persist();render()});$('#favoriteCard')?.addEventListener('click',()=>{const s=cardState(id);s.favorite=!s.favorite;persist();render()});$('#difficultCard')?.addEventListener('click',()=>{const s=cardState(id);s.difficult=!s.difficult;persist();render()});$('#practiceThis')?.addEventListener('click',()=>go('practice/position/'+id))}
  function bindPractice(){const mode=session?.mode;$('#practiceBack')?.addEventListener('click',()=>{session=null;go('practice')});$('#nextPractice')?.addEventListener('click',()=>{session={mode,card:pickPracticeCard(mode==='review'),revealed:false};if(mode==='case')session.case=rand(CASES);render()});$$('[data-choice]').forEach(btn=>btn.onclick=()=>{const choice=session.options[+btn.dataset.choice];const c=session.card;const correctKeys=c.b?[c.a,c.b].sort().join('|'):[c.a].join('|');const got=[...choice].sort().join('|');const ok=got===correctKeys;touchCard(c.id,'practice',ok);state.practiceCount++;persist();const f=$('#practiceFeedback');f.innerHTML=`<div class="feedback"><strong>${ok?'Correcto':'Todavía no'}</strong><br>${esc(c.title)} · ${esc(c.glyphA)} ${esc(c.signA)}${c.signB?` + ${esc(c.glyphB)} ${esc(c.signB)}`:''}<br>${esc(c.idea)}</div>`;$$('[data-choice]').forEach(x=>x.disabled=true)});$('#revealPractice')?.addEventListener('click',()=>{session.answer=$('#practiceAnswer')?.value||'';session.revealed=true;if(session.mode==='surprise')session.cards.forEach(c=>touchCard(c.id,'practice',null));else if(session.mode==='case'){session.case.cards.forEach(id=>touchCard(id,'practice',null));state.caseCount++}else touchCard(session.card.id,'practice',null);state.practiceCount++;persist();render()})}
  function bindJournal(){$('#saveJournal')?.addEventListener('click',()=>{const entry={id:'j'+Date.now(),date:$('#jDate').value,theme:$('#jTheme').value,question:$('#jQuestion').value.trim(),spread:$('#jSpread').value,cards:[1,2,3].map(i=>$(`#jCard${i}`).value).filter(Boolean),initial:$('#jInitial').value.trim(),emotions:$('#jEmotions').value.trim(),conclusion:$('#jConclusion').value.trim(),followup:'',createdAt:now()};if(!entry.question&&!entry.cards.length){toast('Añade una pregunta o al menos una carta');return}state.journal.push(entry);entry.cards.forEach(id=>{const s=cardState(id);if(s.status==='not')s.status='seen'});persist();toast('Lectura guardada');render()});$('#journalSearch')?.addEventListener('input',e=>{$('#journalList').innerHTML=journalListHtml(e.target.value);bindJournalActions()});bindJournalActions()}
  function bindJournalActions(){$$('[data-delete-j]').forEach(b=>b.onclick=()=>{if(confirm('¿Eliminar esta lectura?')){state.journal=state.journal.filter(j=>j.id!==b.dataset.deleteJ);persist();render()}});$$('[data-follow]').forEach(b=>b.onclick=()=>{const j=state.journal.find(x=>x.id===b.dataset.follow);if(!j)return;const v=prompt('Seguimiento días después:',j.followup||'');if(v!==null){j.followup=v;persist();render()}})}
  function bindSettings(){$('#settingsAccount')?.addEventListener('click',accountAction);$('#settingsTheme')?.addEventListener('click',toggleTheme);$('#settingsFont')?.addEventListener('click',toggleFont);$('#resetLocal')?.addEventListener('click',()=>{if(confirm('Esto reinicia el progreso local de Symbolon. ¿Continuar?')){localStorage.removeItem(STORAGE);location.reload()}})}

  function showModal(inner){$('#modalHost').innerHTML=`<div class="modal-backdrop"><div class="modal"><button class="modal-close" id="modalClose">×</button>${inner}</div></div>`;$('#modalClose').onclick=closeModal;$('.modal-backdrop').onclick=e=>{if(e.target.classList.contains('modal-backdrop'))closeModal()}}
  function closeModal(){$('#modalHost').innerHTML=''}
  async function accountAction(){if(!cloud.configured){showModal(`<h2 style="font-family:var(--serif);font-weight:400">Supabase no configurado</h2><p>Completa <code>cloud-config.js</code> y ejecuta <code>SUPABASE_SETUP.sql</code>.</p>`);return}if(cloud.user){showModal(`<h2 style="font-family:var(--serif);font-weight:400">${esc(cloud.user.email||'Cuenta')}</h2><p>Tu progreso está sincronizado.</p><button class="primary" id="signOutNow">Cerrar sesión</button>`);setTimeout(()=>{$('#signOutNow')?.addEventListener('click',async()=>{await Cloud.signOut();closeModal();toast('Sesión cerrada')})},0);return}showModal(`<h2 style="font-family:var(--serif);font-weight:400">Entrar por email</h2><p>Recibirás un enlace mágico. No necesitas contraseña.</p><div class="field"><label>Email</label><input id="loginEmail" type="email" placeholder="tu@email.com"></div><button class="primary" id="sendMagic">Enviar enlace</button><div id="loginStatus" style="margin-top:10px;color:var(--muted)"></div>`);setTimeout(()=>{$('#sendMagic')?.addEventListener('click',async()=>{const email=$('#loginEmail').value.trim();if(!email)return;$('#loginStatus').textContent='Enviando…';try{await Cloud.signIn(email);$('#loginStatus').textContent='Enlace enviado. Abre el email en este dispositivo.'}catch(e){$('#loginStatus').textContent=e.message||'No se pudo enviar'}})},0)}
  function toggleTheme(){state.theme=state.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=state.theme;persist(false);if(currentRoute()==='settings')render()}
  function toggleFont(){state.large=!state.large;document.body.classList.toggle('large',state.large);persist(false);if(currentRoute()==='settings')render()}

  let audio=null,audioModule=null;
  function startAudio(id,title){const src=AUDIO[id];if(!src){toast('Audio pendiente de generar');return}if(audio){audio.pause();audio=null}audio=new Audio(src);audioModule=id;audio.playbackRate=+($('#audioRate')?.value||1);$('#player').hidden=false;$('#audioTitle').textContent=`Módulo ${id.replace('m','')} · ${title}`;$('#audioStatus').textContent='Cargando audio ALEX…';audio.addEventListener('canplay',()=>{$('#audioStatus').textContent='Listo';audio.play().catch(()=>{})},{once:true});audio.addEventListener('play',()=>{$('#audioPlay').textContent='❚❚';$('#audioStatus').textContent='Reproduciendo'});audio.addEventListener('pause',()=>{$('#audioPlay').textContent='▶';if(!audio.ended)$('#audioStatus').textContent='Pausado'});audio.addEventListener('timeupdate',()=>{if(audio.duration)$('#audioProgress').style.width=(audio.currentTime/audio.duration*100)+'%'});audio.addEventListener('ended',()=>{$('#audioPlay').textContent='▶';$('#audioStatus').textContent='Finalizado'});audio.addEventListener('error',()=>{$('#audioStatus').textContent='Audio pendiente: genera los MP3 con el workflow de GitHub';toast('Este módulo todavía no tiene MP3 generado')})}
  $('#audioPlay').onclick=()=>{if(!audio)return;if(audio.paused)audio.play();else audio.pause()};$('#audioStop').onclick=()=>{if(audio){audio.pause();audio.currentTime=0}};$('#playerClose').onclick=()=>{if(audio)audio.pause();$('#player').hidden=true};$('#audioRate').onchange=e=>{if(audio)audio.playbackRate=+e.target.value};

  $('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#themeBtn').onclick=toggleTheme;$('#fontBtn').onclick=toggleFont;$('#accountBtn').onclick=accountAction;
  let deferredPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').style.display='inline-block'});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}else toast('En Safari/Chrome usa “Añadir a pantalla de inicio”')};
  window.addEventListener('hashchange',render);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
  if('serviceWorker' in navigator){navigator.serviceWorker.getRegistrations().then(rs=>rs.forEach(r=>r.unregister()));} if('caches' in window){caches.keys().then(ks=>ks.forEach(k=>caches.delete(k)));}
  render();
})();
