window.SYMBOLON_CASES = [
  {id:'case1',theme:'Relación de pareja',question:'¿Qué patrón interno se activa cuando siento que mi pareja se distancia?',cards:['c18','c67','c04'],positions:['Problema','Camino','Resultado'],keys:['pertenencia','vínculo','libertad','cuidado'],reasoning:'La lectura no intenta confirmar qué piensa la pareja. Parte de tu experiencia interna. La Familia como problema puede mostrar que vínculo y pertenencia se han vuelto una medida de seguridad. La Separación como camino pide diferenciar amor de fusión y tolerar espacio. La Madre como resultado sugiere recuperar una forma de cuidado que no dependa de controlar la distancia del otro.'},
  {id:'case2',theme:'Bloqueo profesional',question:'¿Qué necesito reconocer detrás de mi miedo a mostrar mi trabajo?',cards:['c27','c51','c05'],positions:['Problema','Camino','Resultado'],keys:['imagen','mente','estrategia','expresión'],reasoning:'El Actor como problema puede señalar que mostrarte se ha convertido en representar un personaje perfecto. El Estratega como camino pide ordenar, ensayar y separar preparación de identidad. El Ego como resultado recupera la posibilidad de ocupar espacio creativo sin confundir visibilidad con valor personal.'},
  {id:'case3',theme:'Decisión',question:'¿Qué dinámica interna me hace aplazar una decisión importante?',cards:['c44','c42','c10'],positions:['Problema','Camino','Resultado'],keys:['apego','riesgo','límite','responsabilidad'],reasoning:'El Apego nombra la dificultad de soltar una seguridad conocida. El Loco Absoluto como camino no significa actuar sin criterio, sino detectar dónde la necesidad de certeza es imposible de satisfacer y hacer un movimiento experimental. El Maestro como resultado pide convertir la experiencia en estructura y responsabilidad.'},
  {id:'case4',theme:'Patrón repetitivo',question:'¿Qué parte de mí participa en relaciones donde termino agotado?',cards:['c38','c07','c59'],positions:['Problema','Camino','Resultado'],keys:['poder','reciprocidad','culpa','límites'],reasoning:'El Vampiro como problema invita a mirar intercambios de energía y dependencia sin reducirlos a culpables externos. La Pareja como camino pide reciprocidad explícita y negociación. El Castigo como resultado advierte que, si no se integra el límite, la relación puede acabar convertida en reproche o autocastigo.'},
  {id:'case5',theme:'Conflicto familiar',question:'¿Qué necesito ver en un conflicto que se repite con mi familia?',cards:['c20','c13','c21'],positions:['Problema','Camino','Resultado'],keys:['memoria','autonomía','protección','frialdad'],reasoning:'Mnemosine como problema puede indicar que la disputa actual está cargada de historia y relato familiar. El Desafío como camino pide una separación activa de expectativas heredadas. La Reina de Hielo como resultado muestra el riesgo de resolver autonomía mediante congelación emocional; también puede señalar una distancia protectora temporal que después deberá revisarse.'},
  {id:'case6',theme:'Miedo',question:'¿Qué está organizando mi miedo a equivocarme?',cards:['c61','c06','c51'],positions:['Problema','Camino','Resultado'],keys:['control','perfección','método','pensamiento'],reasoning:'El Miedo como problema sitúa la tensión entre control y libertad. El Servidor como camino pide transformar ansiedad difusa en criterios, pasos y revisión concreta. El Estratega como resultado muestra una mente más capaz de anticipar sin quedar atrapada en la anticipación.'},
  {id:'case7',theme:'Propósito',question:'¿Qué necesito integrar para que mi trabajo tenga más sentido?',cards:['c73','c11','c65'],positions:['Problema','Camino','Resultado'],keys:['verdad','libertad','sentido','integración'],reasoning:'La Confesión como problema puede señalar una verdad personal que todavía no está dicha. El Bufón como camino abre espacio para experimentar una forma más auténtica. El Symbolon como resultado no promete una vocación perfecta: sugiere reunir partes que antes trabajaban separadas.'},
  {id:'case8',theme:'Dinero',question:'¿Qué patrón interno afecta a mi relación con la seguridad económica?',cards:['c45','c02','c48'],positions:['Problema','Camino','Resultado'],keys:['seguridad','valor','responsabilidad','creación'],reasoning:'La Jaula Dorada como problema muestra que una seguridad cómoda puede convertirse en límite. El Amante como camino recupera la pregunta por lo que realmente valoras, no solo por lo que retienes. Responsabilidad por la Creación como resultado pide sostener de forma adulta lo que produces y posees.'},
  {id:'case9',theme:'Creatividad',question:'¿Qué bloquea una idea que deseo sacar al mundo?',cards:['c55','c29','c74'],positions:['Problema','Camino','Resultado'],keys:['bloqueo','poder creativo','cambio','salto'],reasoning:'La Aflicción puede mostrar pensamiento atrapado por exigencia o límites. El Mago como camino pide usar intensidad y creatividad de forma consciente, haciendo algo concreto con el material disponible. El Salto Cuántico como resultado representa la posibilidad de que una estructura cambie de nivel cuando ya existe suficiente trabajo acumulado.'},
  {id:'case10',theme:'Cambio vital',question:'¿Qué necesito comprender para atravesar un cambio que no he elegido?',cards:['c32','c71','c78'],positions:['Problema','Camino','Resultado'],keys:['caída','regeneración','sentido','pregunta'],reasoning:'La Caída como problema confronta con una identidad o estructura que ya no se sostiene. El Fénix como camino pide atravesar la transformación sin reconstruir demasiado pronto lo anterior. La Pregunta del Grial como resultado desplaza el foco: quizá el cierre no sea una respuesta, sino una pregunta más verdadera sobre el sentido de la etapa.'}
];
